# --- CONFIG --- #
# As usual, do not use TAB #

# Ph2ACF output contains more than one OpticalGroup
INPUT_FILE    : /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Run_3/Results.root

# Monitor histogram file
DQM_FILE      : /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Run_3/MonitorDQM_2025-09-03_14-07-41.root


# Where to save the output ROOT files per OpticalGroup
OUTPUT_PATH   : /Users/gsaha/Work/IPHC/TrackerUpgrade/Output/Split_output

# Ladder Information (Same as DCA)
# e.g. plus_<nCoolingPoints>CP_<#Ladder>
LADDER   : plus_6CP_5

# CO2 cooling temperature
# e.g. plus_15_deg / zero_deg / minus_30_deg
COOLING_TEMP : plus_15_deg

# Module positions
# BE CAREFUL! These Module IDs	will be	added as ModuleName inside the ROOT files for each Optical Group
MODULE_POS:
  OpticalGroup_0  : 2S_18_6_BRN-10011
  OpticalGroup_1  : 2S_18_6_AAC-10002
  OpticalGroup_2  : 2S_18_6_AAC-10038 # one screw not connected : recommended (broken bridge)
  OpticalGroup_3  : 2S_18_6_AAC-10004
  OpticalGroup_4  : 2S_18_6_AAC-10027
  OpticalGroup_5  : 2S_18_6_AAC-10005
  OpticalGroup_6  : 2S_18_6_AAC-10003
  OpticalGroup_7  : 2S_18_5_NCP-10001
  OpticalGroup_8  : 2S_18_5_NCP-10005
  OpticalGroup_9  : 2S_18_5_NCP-10004
  OpticalGroup_10 : 2S_18_6_AAC-10006
  OpticalGroup_11 : 2S_18_5_NCP-10003

EXTRA_INFO:
  Setup        : "Ph2-ACF"
  RunNo        : 1
  ResultFolder : Results
  Location     : Strasbourg
  Operator     : IPHC
  RunType      : mod_int
  StationName  : Coldbox
  LadderSlot   : 1
  Comment      : OK