maintag: IPHC_ColdBox_L7

ladder: yes
single_module_box: no

n_boards: 1
n_opticals: 12
n_opticals_start: 0
n_opticals_stop: 12

moduleinfo:
  board_0_optical_0: 2S_18_5_NIS-10018
  board_0_optical_1: 2S_18_6_AAC-10014
  board_0_optical_2: 2S_18_6_AAC-10013
  board_0_optical_3: 2S_18_6_AAC-10012
  board_0_optical_4: 2S_18_6_AAC-10011
  board_0_optical_5: 2S_18_6_AAC-10010
  board_0_optical_6: 2S_18_6_AAC-10009
  board_0_optical_7: 2S_18_6_AAC-10007
  board_0_optical_8: 2S_18_6_BRN-10094
  board_0_optical_9: 2S_18_6_BRN-10042
  board_0_optical_10: 2S_18_6_BRN-10044
  board_0_optical_11: 2S_18_6_BRN-10081


# strip noise histogram names (hybrid level)
strip_noise_hname_hybrid_level:
 - StripChannelNoise
strip_noise_hname_hybrid_level_bottom:
 - StripChannelNoiseBottom
strip_noise_hname_hybrid_level_top:
 - StripChannelNoiseTop

# strip noise histogram names (chip level)
strip_noise_hname_chip_level:
 - ChannelNoise
strip_noise_hname_chip_level_bottom:
 - ChannelNoiseBottom
strip_noise_hname_chip_level_top:
 - ChannelNoiseTop

# common noise histogram names (hybrid level)
common_noise_hname_hybrid_level:
 - CommonNoiseHits_OccupancyDriven
common_noise_hname_hybrid_level_bottom:
 - CommonNoiseHitsBottom_OccupancyDriven
common_noise_hname_hybrid_level_top:
 - CommonNoiseHitsTop_OccupancyDriven

# common noise histogram names (chip level)
common_noise_hname_chip_level:
 - CommonNoiseHits_OccupancyDriven
common_noise_hname_chip_level_bottom:
 - CommonNoiseHitsBottom_OccupancyDriven
common_noise_hname_chip_level_top:
 - CommonNoiseHitsTop_OccupancyDriven

# common noise module level
common_noise_hname_module_level:
 - CommonNoiseHits_OccupancyDriven
common_noise_hname_module_level_bottom:
 - CommonNoiseHitsBottom_OccupancyDriven
common_noise_hname_module_level_top:
 - CommonNoiseHitsTop_OccupancyDriven


# common noise module level (SigmaNoise_3.00)
common_noise_3sigma_hname_module_level:
 - CommonNoiseHits_SigmaNoise_3.00
common_noise_3sigma_hname_module_level_bottom:
 - CommonNoiseHitsBottom_SigmaNoise_3.00
common_noise_3sigma_hname_module_level_top:
 - CommonNoiseHitsTop_SigmaNoise_3.00

# common noise histogram names (hybrid level : SigmaNoise_3.00)
common_noise_3sigma_hname_hybrid_level:
 - CommonNoiseHits_SigmaNoise_3.00
common_noise_3sigma_hname_hybrid_level_bottom:
 - CommonNoiseHitsBottom_SigmaNoise_3.00
common_noise_3sigma_hname_hybrid_level_top:
 - CommonNoiseHitsTop_SigmaNoise_3.00

# common noise histogram names (chip level : SigmaNoise_3.00)
common_noise_3sigma_hname_chip_level:
 - CommonNoiseHits_SigmaNoise_3.00
common_noise_3sigma_hname_chip_level_bottom:
 - CommonNoiseHitsBottom_SigmaNoise_3.00
common_noise_3sigma_hname_chip_level_top:
 - CommonNoiseHitsTop_SigmaNoise_3.00


# pedestal at CBC level
pede_hname_chip_level:
 - ChannelPedestal
 - ChannelPedestalDistribution



files:
  '+15 deg':
    Run1:
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/TB2S_Ladder_minus_6CP_7-2025_11_18_12_18_00-ambient-2SfullTest/ambient/Results/Run_0/Results.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/TB2S_Ladder_minus_6CP_7-2025_11_18_12_18_00-ambient-2SfullTest/ambient/MonitorResults/MonitorDQM_2025-11-18_12-18-00.root

output: /Users/gsaha/Work/IPHC/TrackerUpgrade/Output