maintag: IPHC_coldBox_L5_0hr

ladder: yes
single_module_box: no

n_boards: 1
n_opticals: 12
n_opticals_start: 0
n_opticals_stop: 12

moduleinfo:
  board_0_optical_0: 2S_18_6_BRN-10011
  board_0_optical_1: 2S_18_6_AAC-10002
  board_0_optical_2: 2S_18_6_AAC-10038 # one screw not connected : recommended (broken bridge)
  board_0_optical_3: 2S_18_6_AAC-10004
  board_0_optical_4: 2S_18_6_AAC-10027
  board_0_optical_5: 2S_18_6_AAC-10005
  board_0_optical_6: 2S_18_6_AAC-10003
  board_0_optical_7: 2S_18_5_NCP-10001
  board_0_optical_8: 2S_18_5_NCP-10005
  board_0_optical_9: 2S_18_5_NCP-10004
  board_0_optical_10: 2S_18_6_AAC-10006
  board_0_optical_11: 2S_18_5_NCP-10003


# strip noise histogram names (hybrid level)
strip_noise_hname_hybrid_level:
 - StripChannelNoise
strip_noise_hname_hybrid_level_bottom:
 - StripChannelNoiseBottom
strip_noise_hname_hybrid_level_top:
 - StripChannelNoiseTop

# strip noise histogram names (chip level)
strip_noise_hname_chip_level:
 - ChannelNoise
strip_noise_hname_chip_level_bottom:
 - ChannelNoiseBottom
strip_noise_hname_chip_level_top:
 - ChannelNoiseTop

# common noise module level
common_noise_hname_module_level:
 - CommonNoiseHits_OccupancyDriven
common_noise_hname_module_level_bottom:
 - CommonNoiseHitsBottom_OccupancyDriven
common_noise_hname_module_level_top:
 - CommonNoiseHitsTop_OccupancyDriven

# common noise histogram names (hybrid level)
common_noise_hname_hybrid_level:
 - CommonNoiseHits_OccupancyDriven
common_noise_hname_hybrid_level_bottom:
 - CommonNoiseHitsBottom_OccupancyDriven
common_noise_hname_hybrid_level_top:
 - CommonNoiseHitsTop_OccupancyDriven

# common noise histogram names (chip level)
common_noise_hname_chip_level:
 - CommonNoiseHits_OccupancyDriven
common_noise_hname_chip_level_bottom:
 - CommonNoiseHitsBottom_OccupancyDriven
common_noise_hname_chip_level_top:
 - CommonNoiseHitsTop_OccupancyDriven



# common noise module level (SigmaNoise_3.00)
common_noise_3sigma_hname_module_level:
 - CommonNoiseHits_SigmaNoise_3.00
common_noise_3sigma_hname_module_level_bottom:
 - CommonNoiseHitsBottom_SigmaNoise_3.00
common_noise_3sigma_hname_module_level_top:
 - CommonNoiseHitsTop_SigmaNoise_3.00

# common noise histogram names (hybrid level : SigmaNoise_3.00)
common_noise_3sigma_hname_hybrid_level:
 - CommonNoiseHits_SigmaNoise_3.00
common_noise_3sigma_hname_hybrid_level_bottom:
 - CommonNoiseHitsBottom_SigmaNoise_3.00
common_noise_3sigma_hname_hybrid_level_top:
 - CommonNoiseHitsTop_SigmaNoise_3.00

# common noise histogram names (chip level : SigmaNoise_3.00)
common_noise_3sigma_hname_chip_level:
 - CommonNoiseHits_SigmaNoise_3.00
common_noise_3sigma_hname_chip_level_bottom:
 - CommonNoiseHitsBottom_SigmaNoise_3.00
common_noise_3sigma_hname_chip_level_top:
 - CommonNoiseHitsTop_SigmaNoise_3.00



# pedestal at CBC level
pede_hname_chip_level:
 - ChannelPedestal
 - ChannelPedestalDistribution



files:
  '+15 deg':
    Run1:
      #tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Run_11/Results.root
      #tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Run_11/MonitorDQM_2025-09-05_11-17-13.root
      tfile_main: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Run_3/Results.root
      tfile_dqm: /Users/gsaha/Work/IPHC/TrackerUpgrade/Inputs/Run_3/MonitorDQM_2025-09-03_14-07-41.root

output: /Users/gsaha/Work/IPHC/TrackerUpgrade/Output