# config for OT Physics

# Input file
INPUT_FILE: "/eos/project/i/iphctau/public/gsaha/TrackerUpgrade/OTPhysicsPh2acfFlatRootFiles/run_000049_Board000__one_mods__in_ladder__Flat.root"

# Outdir
OUTPUT: "/eos/project/i/iphctau/public/gsaha/TrackerUpgrade/OTPhysicsOuput/Output"

# signal freq
FS: 10000 #Hz
