# config for OT Physics

# Input file
INPUT_FILE: /eos/project/i/iphctau/public/gsaha/TrackerUpgrade/OTPhysicsPh2acfFlatRootFiles/run_000051_Board000_Ladder_lpGBTv2_1kHz_2sigma_Flat.root

# Outdir
OUTPUT: /eos/project/i/iphctau/public/gsaha/TrackerUpgrade/OTPhysicsOuput/Output

# signal freq
FS: 1000 #Hz

# out-tag
OUTTAG: 1kHz__2_sigma__Ladder__lpGBT_v2__12_Mods__p15